name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      sha:
        description: commit to be deployed
        required: false
  
jobs:
  TestJob:
    name: Test-Job 
    runs-on: ubuntu-latest
    steps:
      - name: Test-Step
        run: echo "Testing ${{ github.events.inputs.sha || github.sha }}"
      
