name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      sha:
        description: commit to be deployed
        required: false
      
      manual:
        description: input flag for manual deployment
        required: false
        default: 'false'
  
jobs:
  TestJob:
    name: Test-Job 
    runs-on: ubuntu-latest
    outputs:
      auto-deploy: ${{ steps.check-benchmarks.outputs.benchmark-status }}
    steps:
      - name: Test-Step
        run: echo "Testing ${{ github.events.inputs.sha || github.sha }}"
      
      - id: check-benchmarks
        run: |
          echo "benchmark-status=${{github.events.inputs.manual}} >> $GITHUB_OUTPUT
      
  AutoDeploy:
    name: Auto-Deploy 
    runs-on: ubuntu-latest
    needs: TestJob
    if: ${{ needs.TestJob.outputs.auto-deploy == 'true' }}
    steps:
      - name: Auto-Deploy
        run: echo "Auto Deploying ${{ github.events.inputs.sha || github.sha }}"
        
        
  ManualDeploy:
    name: Manual-Deploy 
    runs-on: ubuntu-latest
    needs: TestJob
    environment: deployment
    if: ${{ needs.TestJob.outputs.auto-deploy == 'true' }}
    steps:
      - name: Auto-Deploy
        run: echo "Auto Deploying ${{ github.events.inputs.sha || github.sha }}"
          
          
      
      
